[package]
name = "mw-core"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lib]
name = "mw_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
mw-sdk = { path = "../mw-sdk" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
windows-sys = { workspace = true }
retour = { workspace = true }
